# Generated by Django 3.2.9 on 2021-12-03 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_tweet_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
