# Generated by Django 3.2.9 on 2021-12-03 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_tweet_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='hashtags',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='tweet',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='twitter.tweet'),
        ),
    ]
