# Generated by Django 3.2.9 on 2021-12-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_auto_20211203_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='content',
            field=models.CharField(max_length=280),
        ),
    ]
