# Generated by Django 3.2.9 on 2021-12-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0008_alter_hashtag_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='content',
            field=models.CharField(max_length=279),
        ),
    ]
